services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - msa-network
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - msa-network

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
      - .env
      - ./services/auth-service/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - msa-network

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "${USER_PORT}:${USER_PORT}"
    env_file:
      - .env
      - ./services/user-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - msa-network

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
      - ./gateway/.env
    depends_on:
      - auth-service
      - user-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - msa-network


networks:
  msa-network:
    driver: bridge
