services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${NEW_DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - msa-network

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - msa-network

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - '${AUTH_PORT}:${AUTH_PORT}'
    env_file:
      - .env
      - ./services/auth-service/.env
    depends_on:
      - postgres-db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - msa-network

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - '${USER_PORT}:${USER_PORT}'
    env_file:
      - .env
      - ./services/user-service/.env
    depends_on:
      - postgres-db
    networks:
      - msa-network

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
      - ./gateway/.env
    depends_on:
      - auth-service
      - user-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - msa-network

volumes:
  postgres_data:

networks:
  msa-network:
    driver: bridge