#services:
#  auth-service:
#    build:
#      context: .
#    container_name: auth-service
#    env_file:
#      - .env  # ✅ 루트 .env 사용
#    environment:
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      DB_NAME: ${DB_NAME}
#      SERVICE_PORT: ${SERVICE_PORT}
#    ports:
#      - "${SERVICE_PORT}:${SERVICE_PORT}"
#    working_dir: /app
#    command: npm run start
#    volumes:
#      - .:/app
#      - /app/node_modules  # ✅ 호스트 node_modules 덮어쓰기 방지
#    depends_on:
#      - redis
#      - db
#
#  db:
#    image: postgres:13
#    container_name: postgres-db
#    env_file:
#      - .env
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - "5433:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#  redis:
#    image: redis:7
#    container_name: redis
#    ports:
#      - "6379:6379"
#volumes:
#  pgdata:
